In [1]:
import pandas as pd

In [20]:
df_producao = pd.read_csv('dados_originais/tb_producao_2022-05-01_2022-06-30.csv')
colunas = ['Material',
           'Qtd.boa confirm.',
           'Dt.lçto.']
df_producao = df_producao[colunas]
df_producao = df_producao.iloc[:-3]
df_producao

         Material  Qtd.boa confirm.    Dt.lçto.
0       1H65600T1                30  2022-05-01
1       1H65600T1                30  2022-05-01
2       1H65600T1                30  2022-05-01
3       1H65600T1                30  2022-05-01
4       1H65600T1                30  2022-05-01
...           ...               ...         ...
113030    6H76620                50  2022-06-30
113031    6H76620                50  2022-06-30
113032    6H76620                50  2022-06-30
113033    6H76620                50  2022-06-30
113034    6H76620                50  2022-06-30

[113035 rows x 3 columns]

In [22]:
df_consumo_ferramenta = pd.read_csv('dados_originais/tb_consumo_ferramentas_2022-03-01_2026-02-28.csv')

# colunas = ['Material',
#            'Qtd.boa confirm.',
#            'Dt.lçto.']
# df_producao = df_producao[colunas]
df_consumo_ferramenta = df_consumo_ferramenta.iloc[:-7]
df_consumo_ferramenta

C:\Users\gabri\AppData\Local\Temp\ipykernel_11604\1016197608.py:1: DtypeWarning: Columns (0: Tipo de movimento, 1: Nome do usuário, 2: Referência, 3: Pedido) have mixed types. Specify dtype option on import or set low_memory=False.
  df_consumo_ferramenta = pd.read_csv('dados_originais/tb_consumo_ferramentas_2022-03-01_2026-02-28.csv')

,Material,Texto breve material,Lote,Data de lançamento,Qtd. UM registro,Montante em MI,Tipo de movimento,Nome do usuário,Hora do registro,Data de entrada,...,Unid.prç.pedido,Referência,Centro custo,Fornecedor,Pedido,Item,Texto cab.documento,Motivo do movimento,Reserva,Unnamed: 23
0,31_000008769,INSERTO VNMG 12T304-NF IC907,NaN,2024-08-24,-1.0,-35.98,201,310001144,23:59:59,2024-08-23,...,NaN,NaN,3100128.0,NaN,NaN,0.0,NaN,0.0,9.765950e+08,NaN
1,31_000009799,INSERTO TNMG 160412-GH MC5125,NaN,2024-08-24,-1.0,-13.79,201,310001144,23:59:59,2024-08-23,...,NaN,NaN,3100128.0,NaN,NaN,0.0,NaN,0.0,9.765950e+08,NaN
2,31_000012717,INSERTO TCMT 110204-SM IC908,NaN,2024-08-24,-1.0,-20.21,201,310001144,23:59:59,2024-08-23,...,NaN,NaN,3100128.0,NaN,NaN,0.0,NaN,0.0,9.765950e+08,NaN
3,31_000020766,PORTA FERR.TGDR 2525-3M,NaN,2024-08-24,-1.0,-593.40,201,310001144,23:59:59,2024-08-23,...,NaN,NaN,3100157.0,NaN,NaN,0.0,NaN,0.0,9.765950e+08,NaN
4,31_000022620,INSERTO NG2M 120RK KC5025,NaN,2024-08-24,-1.0,-85.59,201,310001144,23:59:59,2024-08-23,...,NaN,NaN,3100128.0,NaN,NaN,0.0,NaN,0.0,9.765950e+08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166442,31_000028234,INSERTO SNMG 120408-SA UE6105,NaN,2023-11-04,-2.0,-33.94,201.0,310004071.0,00:00:14,2023-11-04,...,NaN,NaN,3100126.0,NaN,NaN,0.0,NaN,0.0,7.396114e+08,NaN
166443,31_000005305,INSERTO VCMT 160408-SM IC907 - ISCAR,NaN,2025-07-08,-3.0,-108.78,201.0,310004188.0,00:00:09,2025-07-08,...,NaN,NaN,3100172.0,NaN,NaN,0.0,NaN,0.0,1.247307e+09,NaN
166444,31_000022920,INSERTO CCMT 09T308 MM MC7025,NaN,2025-07-08,-8.0,-100.80,201.0,310004188.0,00:00:09,2025-07-08,...,NaN,NaN,3100172.0,NaN,NaN,0.0,NaN,0.0,1.247307e+09,NaN
166445,31_000028163,INSERTO VNMG 160408 MP MC6025,NaN,2025-07-08,-1.0,-23.18,201.0,310004188.0,00:00:09,2025-07-08,...,NaN,NaN,3100172.0,NaN,NaN,0.0,NaN,0.0,1.247307e+09,NaN
166446,31_000020419,FRESA VF-2XLB R050N060S06 (MITSUBISHI ),NaN,2023-06-15,-1.0,-135.24,201.0,310004188.0,00:00:07,2023-06-16,...,NaN,NaN,3100474.0,NaN,NaN,0.0,NaN,0.0,6.254367e+08,NaN