# Análise Exploratória de Dados (EDA)

In [1]:
# importa biblioteca necessária para EDA
import pandas as pd

In [2]:
# importa os dados
df_producao = pd.read_parquet('tb_producao_consolidado.parquet') # importa os dados de produção
df_consumo_ferramentas = pd.read_parquet('tb_consumo_ferramentas_consolidado.parquet') # importa os dados de consumo de ferramentas

print('--- Informações: df_producao ---' + '\n') # exibe um descritivo do df
df_producao.info() # exibe o .info() do df

print('\n' + '-'*40 + '\n') # exibe um separador

print('--- Informações: df_consumo_ferramentas ---' + '\n') # exibe um descritivo do df
df_consumo_ferramentas.info() # exibe o .info() do df

--- Informações: df_producao ---

<class 'pandas.DataFrame'>
RangeIndex: 2941812 entries, 0 to 2941811
Data columns (total 3 columns):
 #   Column            Dtype
---  ------            -----
 0   Material          str
 1   Qtd.boa confirm.  float64
 2   Dt.lçto.          str
dtypes: float64(1), str(2)
memory usage: 119.2 MB

----------------------------------------

--- Informações: df_consumo_ferramentas ---

<class 'pandas.DataFrame'>
RangeIndex: 166447 entries, 0 to 166446
Data columns (total 3 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Material            166447 non-null  str
 1   Qtd.  UM registro   166447 non-null  float64
 2   Data de lançamento  166447 non-null  str
dtypes: float64(1), str(2)
memory usage: 7.3 MB

Não será necessário realiza limpeza de dados NA por conta do script 'consolidar_arquivos.py' já realiza essa operação durante a consolidação dos dados.

In [8]:
df_producao['Dt.lçto.'] = pd.to_datetime(df_producao['Dt.lçto.'])
df_consumo_ferramentas['Data de lançamento'] = pd.to_datetime(df_consumo_ferramentas['Data de lançamento'])

ValueError: time data "-15281.86" doesn't match format "%Y-%m-%d". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [10]:
df_consumo_ferramentas[df_consumo_ferramentas['Data de lançamento'] == '-15281.86']

           Material  Qtd.  UM registro Data de lançamento
8893   31_000016837              201.0          -15281.86
63144  31_000016837              201.0          -15281.86

In [13]:
df_consumo_ferramentas.loc[range(8880,8894)]

          Material  Qtd.  UM registro Data de lançamento
8880  31_000025924               -1.0         2025-07-12
8881  31_000026158               -1.0         2025-07-12
8882  31_000000095               -1.0         2026-01-05
8883  31_000002148               -1.0         2026-01-05
8884  31_000007118               -2.0         2026-01-05
8885  31_000007543               -2.0         2026-01-05
8886  31_000011642               -2.0         2026-01-05
8887  31_000011887               -1.0         2026-01-05
8888  31_000012174               -1.0         2026-01-05
8889  31_000012176               -1.0         2026-01-05
8890  31_000012180               -1.0         2026-01-05
8891  31_000013410               -1.0         2026-01-05
8892  31_000014586               -1.0         2026-01-05
8893  31_000016837              201.0          -15281.86